version: '3.8'

services:
  migration-assistant:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MIGRATION_LOG_LEVEL=INFO
      - MIGRATION_BACKUP_ENABLED=true
      - MIGRATION_PERFORMANCE_ENGINE=go
    volumes:
      - ./config:/app/config:ro
      - ./backups:/app/backups
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: migration_assistant
      POSTGRES_USER: migration_user
      POSTGRES_PASSWORD: migration_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data: